package com.serthekiller.permadeath.end;

import com.serthekiller.permadeath.mobs.EnderMobs;
import net.minecraft.core.BlockPos;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.resources.ResourceKey;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.boss.enderdragon.EndCrystal;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.dimension.end.EndDragonFight;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/**
 * End crystal regeneration (Fabric EndCrystalMixin): while a dragon is alive in a level, every registered
 * crystal that disappears spawns an Ender Ghast (wither spawn sound) and regenerates after 30-240 s (plugin
 * list).
 *
 * <p>Fixes over Fabric, documented in PERMADEATH_AUDIT.md:
 * <ul>
 *     <li>Fabric counted the regeneration delay in ticks but decremented it once per 20 ticks, so crystals
 *     came back after 40-100 minutes; the delay is now the plugin list (30, 60, 90, 120, 150 or 240 s) in real
 *     ticks.</li>
 *     <li>The check ran from the tick of the remaining crystals, so destroying the last crystal froze every
 *     pending regeneration; it now runs from the level tick.</li>
 *     <li>Only pillar crystals (with visible base, as generated by the spike feature or regenerated here) are
 *     registered: crystals placed by players, e.g. the four used to respawn the dragon, which vanilla removes
 *     when the new dragon appears, no longer spawn ghasts and regenerate on the exit portal.</li>
 *     <li>Crystals in chunks whose entities are not loaded are not taken as destroyed, and an unloaded dragon
 *     (players away from the arena) does not reset the pending regenerations, so relogging or leaving the
 *     End no longer spawns an Ender Ghast per missing crystal again.</li>
 * </ul>
 * Registered positions are kept in memory as in Fabric.
 */
public final class EndCrystals {
    private static final int CHECK_INTERVAL = 20;
    /** Plugin EndDataManager EnderCrystalRegenTime (seconds), one picked at random per crystal. */
    private static final int[] REGEN_SECONDS = {60, 90, 120, 30, 240, 150};

    private static final class Pending {
        final BlockPos pos;
        int ticksRemaining;

        Pending(BlockPos pos, int ticksRemaining) {
            this.pos = pos;
            this.ticksRemaining = ticksRemaining;
        }
    }

    private static final Map<ResourceKey<Level>, Set<BlockPos>> REGISTERED = new HashMap<>();
    private static final Map<ResourceKey<Level>, Map<BlockPos, Pending>> PENDING = new HashMap<>();

    private EndCrystals() {
    }

    public static void reset() {
        REGISTERED.clear();
        PENDING.clear();
    }

    /** Fabric: HEAD of EndCrystal#tick registers the crystal position. */
    public static void onCrystalTick(EndCrystal crystal) {
        if (crystal.level() instanceof ServerLevel level && crystal.showsBottom()) {
            REGISTERED.computeIfAbsent(level.dimension(), k -> new HashSet<>()).add(crystal.blockPosition());
        }
    }

    public static void onLevelTick(ServerLevel level) {
        Set<BlockPos> registered = REGISTERED.get(level.dimension());
        if (registered == null || registered.isEmpty() || level.getGameTime() % CHECK_INTERVAL != 0) {
            return;
        }
        Map<BlockPos, Pending> pending = PENDING.computeIfAbsent(level.dimension(), k -> new LinkedHashMap<>());
        if (!EnderMobs.isDragonAlive(level)) {
            // A dragon that is only unloaded (nobody near the arena) keeps its pending regenerations.
            if (dragonKilled(level)) {
                pending.clear();
            }
            return;
        }
        Set<BlockPos> present = currentCrystals(level);
        for (BlockPos pos : registered) {
            if (!present.contains(pos) && !pending.containsKey(pos) && entitiesLoaded(level, pos)) {
                // Plugin: the Ender Ghast appears 10 blocks above the crystal (not inside the pillar cage).
                EnderMobs.spawnEnderGhast(level, pos.getX() + 0.5, pos.getY() + 10.0, pos.getZ() + 0.5);
                level.playSound(null, pos, SoundEvents.WITHER_SPAWN, SoundSource.MASTER, 100.0F, 2.0F);
                pending.put(pos, new Pending(pos, REGEN_SECONDS[level.getRandom().nextInt(REGEN_SECONDS.length)] * 20));
            }
        }
        Iterator<Pending> it = pending.values().iterator();
        while (it.hasNext()) {
            Pending entry = it.next();
            entry.ticksRemaining -= CHECK_INTERVAL;
            if (entry.ticksRemaining > 0 || !entitiesLoaded(level, entry.pos)) {
                continue;
            }
            if (!present.contains(entry.pos)) {
                regenerate(level, entry.pos);
            }
            it.remove();
        }
    }

    /** Crystals of chunks whose entities are not loaded are invisible, not destroyed. */
    private static boolean entitiesLoaded(ServerLevel level, BlockPos pos) {
        return level.areEntitiesLoaded(ChunkPos.asLong(pos));
    }

    private static boolean dragonKilled(ServerLevel level) {
        EndDragonFight fight = level.getDragonFight();
        return fight == null || fight.saveData().dragonKilled();
    }

    private static Set<BlockPos> currentCrystals(ServerLevel level) {
        Set<BlockPos> present = new HashSet<>();
        for (EndCrystal crystal : level.getEntities(EntityType.END_CRYSTAL, c -> true)) {
            present.add(crystal.blockPosition());
        }
        return present;
    }

    private static void regenerate(ServerLevel level, BlockPos pos) {
        for (BlockPos check : BlockPos.betweenClosed(pos.offset(-1, 0, -1), pos.offset(1, 1, 1))) {
            if (level.getBlockState(check).is(Blocks.FIRE)) {
                level.removeBlock(check.immutable(), false);
            }
        }
        EndCrystal crystal = new EndCrystal(EntityType.END_CRYSTAL, level);
        crystal.setPos(pos.getX() + 0.5, pos.getY(), pos.getZ() + 0.5);
        crystal.clearFire();
        level.addFreshEntity(crystal);
        level.sendParticles(ParticleTypes.PORTAL, pos.getX() + 0.5, pos.getY() + 1, pos.getZ() + 0.5, 50, 0.5, 1.0, 0.5, 0.1);
        level.playSound(null, pos, SoundEvents.END_PORTAL_SPAWN, SoundSource.BLOCKS, 1.0F, 1.0F);
    }
}
