package com.serthekiller.permadeath.worldgen;

import com.mojang.serialization.MapCodec;
import net.minecraft.util.KeyDispatchDataCodec;
import net.minecraft.world.level.levelgen.DensityFunction;
import net.minecraft.world.level.levelgen.LegacyRandomSource;
import net.minecraft.world.level.levelgen.WorldgenRandom;
import net.minecraft.world.level.levelgen.synth.SimplexNoise;

/**
 * Terrain of The Beginning: flat-topped floating islands between y=180 and y=207 built from four fixed-seed
 * simplex octaves. Identical maths and seeds to the Fabric version so chunks generated by either jar match.
 */
public final class UniformIslandsDensityFunction implements DensityFunction.SimpleFunction {
    public static final UniformIslandsDensityFunction INSTANCE = new UniformIslandsDensityFunction();
    public static final MapCodec<UniformIslandsDensityFunction> CODEC = MapCodec.unit(INSTANCE);
    private static final KeyDispatchDataCodec<UniformIslandsDensityFunction> DISPATCH_CODEC = KeyDispatchDataCodec.of(CODEC);

    private static final SimplexNoise NOISE_1 = noise(12345L);
    private static final SimplexNoise NOISE_2 = noise(67890L);
    private static final SimplexNoise NOISE_3 = noise(11223L);
    private static final SimplexNoise NOISE_4 = noise(54321L);
    private static final double MID_Y = 200.0;
    private static final double TOP_Y = 207.0;
    private static final double BOTTOM_Y = 180.0;
    private static final double SCALE_XZ = 0.006;
    private static final double BASE_THRESHOLD = 0.03;
    private static final double[] TOP_LAYER_STEP_DISTANCE = {3.5, 3.5, 3.5, 3.5, 5.0, 5.0, 5.0};
    private static final double NOISE_GRADIENT_FACTOR = 2.6;
    private static final double[] TOP_LAYER_THRESHOLDS = new double[TOP_LAYER_STEP_DISTANCE.length + 1];
    private static final double EROSION_PER_LAYER_BOTTOM = 0.018;
    private static final double EROSION_PER_LAYER_BOTTOM_FLATTEN = 0.05;
    private static final int FLATTEN_START = 16;

    static {
        TOP_LAYER_THRESHOLDS[0] = BASE_THRESHOLD;
        for (int i = 0; i < TOP_LAYER_STEP_DISTANCE.length; i++) {
            TOP_LAYER_THRESHOLDS[i + 1] = TOP_LAYER_THRESHOLDS[i] + TOP_LAYER_STEP_DISTANCE[i] * SCALE_XZ * NOISE_GRADIENT_FACTOR;
        }
    }

    private UniformIslandsDensityFunction() {
    }

    private static SimplexNoise noise(long seed) {
        WorldgenRandom random = new WorldgenRandom(new LegacyRandomSource(seed));
        random.consumeCount(17292);
        return new SimplexNoise(random);
    }

    @Override
    public double compute(FunctionContext context) {
        double y = context.blockY();
        if (y > TOP_Y || y < BOTTOM_Y) {
            return -1.0;
        }
        double x = context.blockX() * SCALE_XZ;
        double z = context.blockZ() * SCALE_XZ;
        double large = NOISE_1.getValue(x, 0.0, z);
        double medium = NOISE_2.getValue(x * 2.0, 0.0, z * 2.0);
        double small = NOISE_3.getValue(x * 4.0, 0.0, z * 4.0);
        double detail = NOISE_4.getValue(x * 8.0, 0.0, z * 8.0);
        double n = (large + medium * 0.45 + small * 0.07 + detail * 0.02) / 1.54;
        return n - thresholdForLayer(y);
    }

    private static double thresholdForLayer(double y) {
        if (y >= MID_Y) {
            int layer = (int) Math.round(y - MID_Y);
            layer = Math.max(0, Math.min(layer, TOP_LAYER_THRESHOLDS.length - 1));
            return TOP_LAYER_THRESHOLDS[layer];
        }
        int layer = (int) Math.round(MID_Y - y);
        if (layer < FLATTEN_START) {
            return BASE_THRESHOLD + layer * EROSION_PER_LAYER_BOTTOM;
        }
        double atFlattenStart = BASE_THRESHOLD + (FLATTEN_START - 1) * EROSION_PER_LAYER_BOTTOM;
        return atFlattenStart + (layer - FLATTEN_START + 1) * EROSION_PER_LAYER_BOTTOM_FLATTEN;
    }

    /** Density at a block position (used by the structure placement check). */
    public double sample(int x, int y, int z) {
        return compute(new DensityFunction.SinglePointContext(x, y, z));
    }

    @Override
    public double minValue() {
        return -1.0;
    }

    @Override
    public double maxValue() {
        return 1.0;
    }

    @Override
    public KeyDispatchDataCodec<? extends DensityFunction> codec() {
        return DISPATCH_CODEC;
    }
}
